schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/coreos/go-semver"]
    version = "v0.3.1"
    hash = "sha256-ZZPTQW8xCqYk4vERTu/nBvCB9D01xO3XfnyFPb0nQG8="
  [mod."github.com/coreos/go-systemd/v22"]
    version = "v22.5.0"
    hash = "sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA="
  [mod."github.com/dapr/kit"]
    version = "v0.0.0-20241009222632-45e23e402b9d"
    hash = "sha256-SmMYlU2njkzp4JewOSpIDwTpuEfClABKVWrEivaWv0E="
    replaced = "github.com/joshvanl/kit"
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-logr/zapr"]
    version = "v1.3.0"
    hash = "sha256-ehak315/wxBKtuFhCz+TPsvNzYBv0/oZ3tVIjT52hc0="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.0"
    hash = "sha256-dyKL8wQRApkdCkKxJ1knllvixsrBLw+BtRS0SjlN7NQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/google/btree"]
    version = "v1.1.3"
    hash = "sha256-/6Us2eNRFi2IIp7p5uPUXLridilAdk4SmZhcTYR0csw="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.4.0"
    hash = "sha256-0UymBjkg41C9MPqkBLz/ZY9WbimZrabpJk+8C/X63h8="
  [mod."github.com/grpc-ecosystem/go-grpc-prometheus"]
    version = "v1.2.0"
    hash = "sha256-XtdBJuUYTXEokPrUetjD6iEqxFTBgyrm1M0X7r+1Uys="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.22.0"
    hash = "sha256-XiTsDCKK27Wn77deJ6X2ulIjqahXgOxA7t2YCsLltFY="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.4.0"
    hash = "sha256-jj955cmaXwWpk7+ZTUxRds/lSt5ghkyyOesW/yFLM8g="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.10"
    hash = "sha256-OLkMoIaHLIhtDonP0qXf8L+iKB1VBlxm6jOMdjHcvb8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.20.4"
    hash = "sha256-pdyQUDEkBwNmbT6IPtEVqmx7z0kBROvmOMMeeRVHAog="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.59.1"
    hash = "sha256-PYoEunC2Rx1KP8vH2inTD7uBCfUlvcROfeeAGRRjXPY="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/soheilhy/cmux"]
    version = "v0.1.5"
    hash = "sha256-e9+SEcYZONDLDvRfCmwkkpLTTll55LIhhC2bigVO1uc="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/tmc/grpc-websocket-proxy"]
    version = "v0.0.0-20220101234140-673ab2c3ae75"
    hash = "sha256-IAmkyqWNJYIKdgV6iZjefF+qpetkHMNUrtpoJu3AKQk="
  [mod."github.com/xiang90/probing"]
    version = "v0.0.0-20221125231312-a49e3df8f510"
    hash = "sha256-WaW8Hj5HU5ikJ5JuRJ7iE5XYEPASCfqlttj175DnF/A="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.11"
    hash = "sha256-SVWYZtE9TBgAo8xJSmo9DtSwuNa056N3zGvPLDJgiA8="
  [mod."go.etcd.io/etcd/api/v3"]
    version = "v3.5.16"
    hash = "sha256-54NdxG0U4Yb3u3WmYeQ696UXKETe4oYxai4h8H6b1EA="
  [mod."go.etcd.io/etcd/client/pkg/v3"]
    version = "v3.5.16"
    hash = "sha256-gs1Q0QST2aWxNOurkRcfRxZ3G0Ww7ThwZhhYkuYRhEY="
  [mod."go.etcd.io/etcd/client/v2"]
    version = "v2.305.16"
    hash = "sha256-AZnuvp7LsOrDGPXmV8PKbSGvou70o2mTWKjl4hJ8dLw="
  [mod."go.etcd.io/etcd/client/v3"]
    version = "v3.5.16"
    hash = "sha256-qsXRGX6Zyp/8tNKtI5bVG9W1DJQO1uYYGyxOBoX4ZsY="
  [mod."go.etcd.io/etcd/pkg/v3"]
    version = "v3.5.16"
    hash = "sha256-+t3jlbhG/HWmp8KSSHOuShoi/fhDccBaMy9E9mUYNnU="
  [mod."go.etcd.io/etcd/raft/v3"]
    version = "v3.5.16"
    hash = "sha256-cLvRHTOemtdqZjtMiO84Qyiq1sLcnt5pNEYLsXrgfRA="
  [mod."go.etcd.io/etcd/server/v3"]
    version = "v3.5.16"
    hash = "sha256-BLQ43Cnv38trYVvawVWGuSZO7WjFN8pkAUfLak7PEhk="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.55.0"
    hash = "sha256-aiaNqHfnhz0NgjxqKJMILa7JcCRweCjBq8i7EiM2sx4="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.30.0"
    hash = "sha256-2r706a1+LqhT3DNqVZB6NIVaBoPnQ257BJY8UQqtaSM="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.30.0"
    hash = "sha256-YFCsAt8PnB6mONHJqgGJYYeQofye0vxusMIoht/caDc="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.30.0"
    hash = "sha256-pzvCJWgRJ0vFH5bODAhNbEv8+M6QGXzojbXY1kus6jI="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.30.0"
    hash = "sha256-mSfy2A7cxIjAOs9tZ74kgVnsnGZoC3be/MjjFlO8KCw="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.30.0"
    hash = "sha256-a+oojnlDDHnliphPvObLdW2jZjfSDcBF7QkV7H9ZltY="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.30.0"
    hash = "sha256-6YukUeYtMo5jtKsoQQwuy3Zyx1Cl2LRMONnF91PCBIk="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.3.1"
    hash = "sha256-WaXW64jWowTDlNYDHiGKmHzRUrwJ8Rkymyvz7W6UHd8="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/crypto"]
    version = "v0.27.0"
    hash = "sha256-8HP4+gr4DbXI22GhdgZmCWr1ijtI9HNLsTcE0kltY9o="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240909161429-701f63a606c0"
    hash = "sha256-nB3zQGSyCNU9Z6QP0iYYBpUeu7HKBBXS1z9ba4DxjMQ="
  [mod."golang.org/x/net"]
    version = "v0.29.0"
    hash = "sha256-dH9Rdf5T04KJ4B5WvIZh12ogMbADWiWgIt77nvPTk2k="
  [mod."golang.org/x/sys"]
    version = "v0.25.0"
    hash = "sha256-PXZ9EQZ7SFpcL7d3E1+KGTxziYlHEIZPfoXEbnaVD3I="
  [mod."golang.org/x/text"]
    version = "v0.18.0"
    hash = "sha256-aNvJW4gQs+MTfdz6DZqyyHQS2GJ9W8L8qKPVODPn4+k="
  [mod."golang.org/x/time"]
    version = "v0.6.0"
    hash = "sha256-gW9TVK9HjLk52lzfo5rBzSunc01gS0+SG2nk0X1w55M="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20240924160255-9d4c2d233b61"
    hash = "sha256-LwVxvrL7wVusGi5HpQ1xUGIsIBlE+RNVBQOEtclAkn8="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240924160255-9d4c2d233b61"
    hash = "sha256-ft6YxEOIZE9psXdggZl76nZW4UN/YJ/UXfSKjqoy0So="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240924160255-9d4c2d233b61"
    hash = "sha256-4T4DTrmFbqT4tD7PSL7Ie7u8ZN2iwGkhK02nWugssxk="
  [mod."google.golang.org/grpc"]
    version = "v1.67.0"
    hash = "sha256-n/0i7nR+dm0mIkJfUlM1BNcOdkwWBxspr9TQtwHMXV0="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/apimachinery"]
    version = "v0.31.1"
    hash = "sha256-yj8N0Y4OkmdiidrEq76ysqZoYyKTnB4WmfcZp4uR8gY="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20240921022957-49e7df575cb6"
    hash = "sha256-QFwnklx4JnNMcQItXBQ8tc+hylBDBZF8T4+MOFRomvM="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.4.0"
    hash = "sha256-Hd/M0vIfIVobDd87eb58p1HyVOjYWNlGq2bRXfmtVno="
